name: deployment_test_prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - PMZ-Test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file
        run: cp models/formacion_analytics_test.model.lkml models/formacion_analytics.model.lkml
      
      - name: Push Changes
        run: |
          git config --global user.name 'pacomantell'
          git config --global user.email 'paco.mantell94@gmail.com'
          git commit -am "Copy model File"
          git push
