name: deployment_test_prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - PMZ-Test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file
        uses: canastro/copy-file-action@master
        with:
          source: "models/formacion_analytics_test.model.lkml"
          target: "models/formacion_analytics.model.lkml"

